FROM ubuntu:latest AS build

RUN apt update && \
    apt install -y git openjdk-8-jdk

ENV PATH="/usr/lib/jvm/java-8-openjdk-amd64/bin:$PATH"
RUN JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

WORKDIR /src

RUN git clone https://github.com/CloudburstMC/Nukkit

WORKDIR /src/Nukkit

RUN git submodule update --init && \
    ./gradlew shadowJar && \
    mkdir /data && \
    cp /src/Nukkit/target/nukkit-1.0-SNAPSHOT.jar /data/nukkit.jar

FROM ubuntu:latest AS run

RUN apt clean && \
    apt update && \
    apt install -y git openjdk-8-jdk

ENV PATH="/usr/lib/jvm/java-8-openjdk-amd64/bin:$PATH"
RUN JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

WORKDIR /src

RUN git clone https://github.com/CloudburstMC/Nukkit

WORKDIR /src/Nukkit

RUN git submodule update --init && \
    ./gradlew shadowJar && \
    mkdir /data && \
    cp /src/Nukkit/target/nukkit-1.0-SNAPSHOT.jar /data/nukkit.jar

RUN apt install -y language-pack-ja-base language-pack-ja
ENV LANG=ja_JP.UTF-8

# Create minecraft user
RUN useradd --user-group \
            --no-create-home \
            --home-dir /data \
            --shell /usr/sbin/nologin \
            minecraft

# Ports
EXPOSE 19132

RUN mkdir /home/minecraft
RUN chown -R minecraft:minecraft /data /home/minecraft

# User and group to run as
USER minecraft:minecraft

# Volumes
VOLUME /data /home/minecraft

# Set runtime workdir
WORKDIR /data

# Run app
ENTRYPOINT ["java"]
CMD [ "-jar", "/app/nukkit.jar" ]