# 対象の指定(インベントリファイルで指定した名前)
- hosts: server

  # 以下に実際の操作を記述していく
  tasks:
    - name: apt clean
      apt:
        autoclean: yes # すべてのキャッシュファイルを削除
        update_cache: no # アップデートせずにキャッシュをクリア
      register: clean_result

    - name: apt update
      apt:
        update_cache: yes # パッケージリストをアップデート
      register: update_result

    - name: Install UFW,unzip and curl
      become: yes
      apt:
        name:
          - unzip
          - curl
          - ufw
        state: present

    - name: Use curl with Ansible
      tasks:
        - name: Use curl to download a file
          shell: |
            curl -l -O /opt/bedrock \
              https://minecraft.azureedge.net/bin-linux/bedrock-server-1.20.40.01.zip

        - name: Use unzip
          shell: unzip /opt/bedrock/bedrock-server-1.20.40.01.zip

        - name: Delete zip file
          shell: rm /opt/bedrock/bedrock-server-1.20.40.01.zip

    - name: Configure UFW Rules
      become: yes
      tasks:
        - name: Enable UFW
          command: ufw --force enable

        - name: Allow SSH (TCP Port 22)
          command: ufw allow 22/tcp

        - name: Allow UDP Port 19132
          command: ufw allow 19132/udp

        - name: Reload UFW
          command: ufw reload

    # 言語設定の変更
    - name: set LANG=ja_JP.UTF-8 in /etc/locale.conf
      lineinfile:
        dest: /etc/locale.conf
        regexp: "^LANG="
        line: "LANG=ja_JP.UTF-8"
        backup: yes
