- hosts: server
  remote_user: ubuntu
  tasks:
    - name: apt clean
      become: yes
      apt:
        autoclean: yes
        update_cache: no

    - name: apt update and upgrade
      apt:
        update_cache: yes
        upgrade: yes
      become: yes

    - name: Install UFW,unzip and curl
      become: yes
      apt:
        name:
          - unzip
          - curl
          - ufw
        state: present

    - name: Remove previous file
      command: rm -f -r bedrock bedrock-server.zip
      become: yes

    - name: Downlord zip file
      command: curl -o bedrock-server.zip {{ server_url }}
      become: yes

    - name: Unzip server file
      command: unzip bedrock-server.zip -d ~/bedrock

    - name: Remove zip file
      command: rm -f ~/bedrock-server.zip

    - name: Change world difficulty
      command: sed -i "/difficulty=*/s/.*/difficulty=hard/" ~/bedrock/server.properties

    - name: Set world name
      command: sed -i "/server-name=*/s/.*/server-name={{ server_name }}/" ~/bedrock/server.properties

    - name: Enable UFW
      become: yes
      command: ufw --force enable

    - name: Allow SSH (TCP Port 22)
      become: yes
      command: ufw allow 22/tcp

    - name: Allow UDP Port 19132
      become: yes
      command: ufw allow 19132/udp

    - name: Reload UFW
      become: yes
      command: ufw reload

    - name: RUN SERVER
      ansible.builtin.shell:
        cmd: LD_LIBRARY_PATH=. & nohup ./bedrock_server > ~/output.log &
        chdir: ~/bedrock
